version: '3.1'
services:

  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db1234
      MYSQL_DATABASE: test_db
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
   mysql_data:
