version: '3'

services:

  test:
    image: ortussolutions/commandbox
    environment:
      cfconfig_adminPassword: testing
    volumes: 
      - ./test:/app
      - ./build:/root/build
    ports:
      - "8080:8080"
