version: '3'

services:
  # NGINX Container
  web:
    image: nginx
    ports: 
      - "81:80"
      - "443:443"
    # Mount our shared webroot volume
    volumes:
      - commandbox_nginx:/usr/share/nginx/html
      - commandbox_nginx_conf:/etc/nginx/nginx.conf
    links:
      - app:luceehost  
  
  # Application Server
  app:
    image: ortussolutions/commandbox 
    environment:
      PORT: 8080
      SSL_PORT: 8443
    volumes:
      - commandbox_app:/app

  #MySQL
  mysql:
    image: mysql:latest  
    environment:
      MYSQL_ROOT_PASSWORD: "MyS3cur3P455!"
    volumes:
      - commandbox_initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
   commandbox_app:
