version: "2"
services: 
  nginx:
    image: nginx
    build: ./foobar
    ports:
      - "6060:6060/udp"
      - "5000:5000"      
    cap_add:
      - ALL
    container_name: foobar
    labels: 
      kompose.service.type: loadbalancer
