version: '2.1'

services:
  # NGINX Container
  web:
    image: nginx
    ports: 
      - "81:80"
      - "443:443"
    # Mount our shared webroot volume
    volumes:
      - .:/usr/share/nginx/html
      - ./build/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - app:luceehost  
  
  # Application Server
  app:
    image: ortussolutions/commandbox 
    environment:
      PORT: 8080
      SSL_PORT: 8443
    volumes:
      - .:/app

  #MySQL
  mysql:
    image: mysql:latest  
    environment:
      MYSQL_ROOT_PASSWORD: "MyS3cur3P455!"
    volumes:
      - ./build/docker/mysql/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
