services:
  node-red:
    image: nodered/node-red:latest
    deploy:
      mode: replicated
      replicas: 8
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:

networks:
  node-red-net:
