apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yml -o whoami-deployment.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: whoami
      name: whoami
    spec:
      ports:
        - name: "80"
          port: 80
          targetPort: 80
      selector:
        io.kompose.service: whoami
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yml -o whoami-deployment.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: whoami
      name: whoami
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: whoami
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: ./kompose convert -f docker-compose.yml -o whoami-deployment.yaml
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: whoami
        spec:
          containers:
            - image: containous/whoami
              name: whoami
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

